config/routes.rb
Rails.application.routes.draw do

  root 'homepage#show'

  get 'sessions/new' => 'sessions#new', as: :sign_in
  post 'sessions/new' => 'sessions#create'
  delete 'session' => 'sessions#delete', as: :sign_out

  get 'register' => 'registrations#new', as: :sign_up
  post 'register' => 'registrations#create', as: :users

  get 'postcards/new' => 'postcards#new', as: :new_postcard
  post 'postcards' => 'postcards#create', as: :postcards
  get 'postcards/:id' => 'postcards#show', as: :postcard

end

app/models/postcard.rb
class Postcard < ActiveRecord::Base
  attachment :photo
  belongs_to :user

  geocoded_by :location
  after_validation :geocode

  validates :photo, :email_recipient, :user, :message, :location, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :postcards
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    @current_user = User.find_by id: session[:user_id]
  end

  def authenticate_user!
    if @current_user.nil?
      redirect_to sign_in_path, alert: 'Please Sign In'
    end
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  before_action :authenticate_user!

  def show
    @postcards = Postcard.where(user_id: @current_user.id).all
    #@postcards = @current_user.postcards

  end
end

app/controllers/postcards_controller.rb
class PostcardsController < ApplicationController

  before_action :authenticate_user!

  def new
    @postcard = Postcard.new
  end

  def create
    @postcard = Postcard.new params.require(:postcard).permit(:photo, :email_recipient, :message, :location)
    @postcard.user = @current_user
    if @postcard.save
      PostcardsMailer.new_card(@postcard).deliver_now
      redirect_to root_path, notice: 'NOICE'
    else
      render :new
    end
  end

  def show
    @postcard = Postcard.find_by id: params[:id]
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new params.require(:user).permit(:email, :name, :password, :password_confirmation)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @current_user = User.find_by email: params[:email]
    if @current_user && @current_user.authenticate(params[:password])
      session[:user_id] = @current_user.id
      redirect_to root_path, notice: "Welcome Back! You're Signed In!"
    else
      flash.now[:alert] = "There's something wrong with either your email or password"
      render :new
    end
  end

  def delete
    session.delete(:user_id)
    redirect_to root_path, notice: "You are now signed out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/homepage/show.html.erb
 <div id="mapid"></div>

<script type="text/javascript">
$(window).ready(function(){

  var mymap = L.map('mapid').setView([29.73, -95.39], 10);

  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
    maxZoom: 18,
    id: 'jwo-cink.pia181pk',
    accessToken: 'pk.eyJ1IjoiandvLWNpbmsiLCJhIjoiQVBfcW9OOCJ9.k2Q4vbfJs16Idk2cOziQYQ'
}).addTo(mymap);

  <% @postcards.each do |postcard| %>
    L.marker([<%= postcard.latitude %>, <%= postcard.longitude %>]).addTo(mymap)
      .bindPopup('<b><%= postcard.location %></b><br/> <%= image_tag attachment_url(postcard, :photo, :fill, 160, 160), class: "img-responsive" %>  <br /><%= link_to 'View Postcard', postcard_path(id: postcard.id ), class: "btn btn-default btn-block" %>');
  <% end %>



})

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postcards</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.css" media="screen" title="no title" charset="utf-8">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <div class="container">

    <div class="row">

      <div class="col-xs-6">
        <%= link_to 'Home', root_path %>
        <%= link_to 'New Postcard', new_postcard_path, class: 'btn btn-default' %>
      </div>

      <div class="col-xs-6 header-right">
        <% if @current_user.present? %>
          <strong>Hi <%= @current_user.name %></strong>
          <%= link_to 'Sign Out', sign_out_path, method: :delete %>
        <% end %>
      </div>

    </div>

  </div>
</header>

<div class="flashes">

  <% if notice.present? %>
    <div class="alert alert-info"><%= notice %></div>
  <% end %>

  <% if alert.present? %>
    <div class="alert alert-danger"><%= alert %></div>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/postcards/new.html.erb
<div class="container">

  <h1>New Postcard</h1>

  <%= simple_form_for @postcard do |f| %>
    <%= f.input :email_recipient %>
    <%= f.input :message %>
    <%= f.input :photo, as: :file %>
    <%= f.input :location %>

    <%= f.submit class: "btn btn-success btn-lg" %>
  <% end %>
</div>

app/views/postcards/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-xs-8">
        <%= image_tag attachment_url(@postcard, :photo), class: 'img-responsive' %>
    </div>

    <div class="col-xs-4">
      <h1><%= @postcard.location %></h1>
      <%= simple_format @postcard.message %>
    </div>

  </div>




</div>